### ISSUE TITLE
AlertDialog does not show positive and negative button

### ISSUE THREAD

**Issue by ma-za-kpe** [Flutterwave/rave-android#268]
https://github.com/Flutterwave/rave-android/blob/master/rave_android/src/main/java/com/flutterwave/raveandroid/ugmobilemoney/UgMobileMoneyFragment.java on line 201, the buttons do not show because there is no style. 

![bug](https://user-images.githubusercontent.com/28810111/122915210-5db4ce80-d310-11eb-9ff3-07f522df51b9.png)

possible solution is adding a style like here:  https://stackoverflow.com/questions/39481735/alertdialog-do-not-show-positive-and-negative-button

## System Information

 - Operating system:
 - Rave version:

**Comment by MohsinaliEMed** [comment]
i facing same issue

**Comment by anitanCbl** [comment]
I am facing same issue.
Update the text color of alert dialog button.

**Comment by RumitEmed** [comment]
I also have the same issue. No response from **LAST MONTH**. Now moving to another alternative.

Good luck with your **scrap and pathetic payment gateway.**

**Comment by ma-za-kpe** [comment]
This issue has actually been solved, thank you flutter wave team. Although it could have been solved sooner.
![Screenshot_20210810-142953](https://user-images.githubusercontent.com/28810111/128859659-d23915f8-1c83-4b92-81ba-d9645c3e3cc8.png)

**Comment by muazdev26** [comment]
@ma-za-kpe  Hello! Can you please tell me How can you solve this? I am using the latest version but still not getting the "Yes", and "No" buttons.
